### ISSUE TITLE
Action menu not displayed properly in nested Archetype

### ISSUE THREAD

**Issue by abjerner** [imulus/Archetype#175]
I have a nested Archetype in `1.3.1-beta`. Whenever I try to add a new item/fieldset close to the bottom, the action menu is "cropped" as shown on the screenshot below:

![image](https://cloud.githubusercontent.com/assets/3634580/3510944/7a2fe8c6-06ab-11e4-9340-24ca43763bfa.png)

Trying to add a new item in the beginning of the fieldset, the action menu looks fine:

![image](https://cloud.githubusercontent.com/assets/3634580/3511030/44b84ee4-06ac-11e4-9452-51573b052cde.png)

The more items in the action menu, the worse the problem will be. The issue seems to be caused by the following CSS rule:

``` CSS
.archetypeEditor .archetypeProperty {
    clear: both;
    overflow: hidden;
    margin-top: 3px;
}
```

In my small example the issue can be fixed by changing `hidden` to `visible`. But this may need some further testing, which I why I haven't made a pull request.

``` CSS
.archetypeEditor .archetypeProperty {
    clear: both;
    overflow: visible;
    margin-top: 3px;
}
```
